# fly.toml app configuration file generated for emisyon-saha on 2025-01-14T10:30:00Z

app = "emisyon-saha"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"
  builder = "dockerfile"

[env]
  PORT = "8080"
  FLASK_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[mounts]]
  source = "data"
  destination = "/data"

[processes]
  app = "python app.py"
